### ISSUE TITLE
How do we use AWQ checkpoints for faster inference

### ISSUE THREAD

**Issue by rebuttalpapers** [NVlabs/VILA-archive#13]
I used the following command

python -W ignore llava/eval/run_vila.py \
    --model-path Efficient-Large-Model/VILA1.5-3b \
    --conv-mode vicuna_v1 \
    --query "<video>\n Please describe this video." \
    --video-file "demo.mp4"

It seems changing to the AWQ one is not giving benefit for either latency or memory.

python -W ignore llava/eval/run_vila.py \
    --model-path Efficient-Large-Model/VILA1.5-3b-AWQ \
    --conv-mode vicuna_v1 \
    --query "<video>\n Please describe this video." \
    --video-file "demo.mp4"

**Comment by ys-2020** [comment]
Hi @rebuttalpapers , thanks for your interests in VILA and AWQ! Instructions for running VILA with AWQ can be found [here](https://github.com/NVlabs/VILA?tab=readme-ov-file#quantization-and-deployment). You may need to use [TinyChat](https://github.com/mit-han-lab/llm-awq/tree/main/tinychat) for faster inference. You can also find some example commands in this [link](https://github.com/mit-han-lab/llm-awq/tree/main/tinychat#support-visual-language-models-vila-15-vila-llava).

**Comment by Lyken17** [comment]
Hi there,

Our team has moved our VILA to a new location: [NVLabs/VILA](https://github.com/NVlabs/VILA). We kindly request that you update your references to the old repository location with the new one (e.g, git clone / pipeline integration). This will ensure that you have access to the latest updates, improvements, and bug fixes for VILA project. Current repo will be archieved in one week (Jul 10th) and made private after one month (Aug 4th).

Thank you for your understanding and continued support. If your issue still exists, feel free to open a new one in the new place. We appreciate your patience and cooperation during this transition.

Best regards,
VILA Team
