### ISSUE TITLE
Question in demo_trt_llm/run.py code

### ISSUE THREAD

**Issue by ZihaoWang-CV** [NVlabs/VILA-archive#30]
Thank you for the detailed tutorial on model quantization.

I have noticed an inconsistency between the demo_trt_llm implementation in your repo for VILA-1.5 and the official TRT-LLM repository for VILA-1.0.

In your demo code [here](https://github.com/NVlabs/VILA/blob/main/demo_trt_llm/run.py#L350), when adding image embs to the LLM vocab, the image features are duplicated as follows:

`ptuning_args[0] = torch.cat((ptuning_args[0], ptuning_args[0]))
`

I believe this duplication might cause a larger max_multimodal_len when building the TRT model in certain cases like fintuning on more than 8 images.

However, in the official TRT-LLM repository [here](https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/multimodal/run.py#L617) for VILA-1.0, there is no need to duplicate the ptuning_args.

Could you please clarify if this is a special design for the VILA-1.5? Any insights into the rationale behind this discrepancy would be greatly appreciated.

Thank you for your attention to this matter.

**Comment by Lyken17** [comment]
Hi there, 

Our team has moved our VILA to a new location: [NVLabs/VILA](https://github.com/NVlabs/VILA). We kindly request that you update your references to the old repository location with the new one (e.g, git clone / pipeline integration). This will ensure that you have access to the latest updates, improvements, and bug fixes for VILA project. Current repo will be archieved in one week (Jul 10th) and made private after one month (Aug 4th).

Thank you for your understanding and continued support. If your issue still exists, feel free to open a new one in the new place. We appreciate your patience and cooperation during this transition.

Best regards,
VILA Team

**Comment by Efficient-Large-Language-Model** [comment]
We updated the TRT-LLM read me. Please use the official TRT-LLM.
